docs/ui-components/navigation.md
Kicking things off with a definition for the application header. Let me know if you have questions about how to review pull requests.
Reviewers:
@Bluemeredith
@mcaskey
Parker Malenke
=> Add application header definition

_layouts/default.html, docs/ui-components/colors/index.md
=> Initial version of the colors component documentation.

docs/ui-components/colors/index.md
=> Add colors in support of buttons component.

_sass/_article_body.scss, c/breakpoints/beta/index.md
Adds a beta version of the breakpoints component documentation:
http://pearson-higher-ed.github.io/design/c/breakpoints/beta/
=> Add first beta of breakpoints documentation.

_layouts/spec.html, _sass/_spec.scss, _sass/_toc.scss, _sass/typography/_copy.scss, main.scss, membership-spec.md, membership-spec/beta/index.md, membership-spec/index.md
Add beta version of new spec so we can all see it.
=> Finalize spec

getting-started-dev/beta/index.md
Add @aaronkaka 's updates to the dev guide.
=> Getting started guides

_layouts/spec.html, membership-spec/beta/index.md
@aamirali1 @kaadams4 I've started the work of integrating Aamir's document into the Library Membership Specification. I think you guys will need to finish this up though since I'm not as familiar with everything you're trying to achieve with the dev standards/conventions.
Also, it seemed like several sections of the original document aren't really requirements, and should probably be moved into the component creation guide instead.
=> Convert compound creation guide -> membership spec

c/colors/v2.0.0-beta.5/index.md
added 2 colors: sunflower yellow and alto to support button states
=> colors update

c/mobile-quiz-feedback/v1.0.0-beta.1/index.md, c/mobile-quiz-frontMatter/v1.0.0-beta.1/index.md, c/mobile-quiz-item/v1.0.0-beta.1/index.md, c/mobile-quiz-results/v1.0.0-beta.1/index.md
fix to 
mobile-quiz-feedback
mobile-quiz-frontmatter
mobile-quiz-item
mobile-quiz-results
=> fix to mobile-quiz flows

c/inputs/v2.0.0-beta.3/index.md
=> adding password show/hide

getting-started-dev/index.md
https://agile-jira.pearson.com/browse/DES-527
=> docs: DES-527

c/inputs/v2.0.0-beta.4/index.md
Fixed broken link to sketch file.  Removed link to nonexistent AI file.
=> inputs-downloads-link-fix

c/buttons/v2.0.0-beta.4/index.md
Additional do’s and don’ts added to help designers understand when to
use link style buttons.
=> add link style button info

c/buttons/v2.0.0-beta.4/index.md, c/typography/v2.0.0-beta.9/index.md
-fixed typos
-added cross reference links between button and typography spec docs
=> additional edits to link style buttons

c/buttons/v2.0.0-beta.5/index.md
changed “confirmation” to “verification”
=> text change

c/loading-indicator/v1.0.0-beta.1/index.md
added graphic of spinner detail info
=> Loading indicator 1

c/buttons/v2.1.0-beta.2/index.md
=> Button content update

c/pagination/v1.0.0-beta.1/index.md
Modify Dependencies and update color links
=> Modify Dependencies

c/alerts/v1.0.0-beta.5/index.md, c/application-header/v2.0.0/index.md, c/avatar-display/v1.0.0/index.md, c/buttons/v2.0.0/index.md, c/coachmarks/v1.0.0-beta.5/index.md, c/forms/v1.0.0-beta.3/index.md, c/forms/v1.0.0/index.md, c/grid/v1.0.0/index.md, c/icons/v2.0.0-beta.4/index.md, c/icons/v2.0.0/index.md, c/inputs/v2.0.0-beta.3/index.md, c/inputs/v2.0.0/index.md, c/notifications/v1.0.0/index.md, c/presentation-strategies/v1.0.0/index.md, c/slider/v1.0.0-beta.2/index.md, c/templates/v2.0.0-beta.1/index.md, c/typography/v2.0.0-beta.8/index.md, c/typography/v2.0.0-beta.9/index.md
@parkerpearson 
This PR is to update the design site to better reflect what code has been implemented.
=> update component docs with versions implemented

c/loading-indicator/v1.0.0-beta.3/index.md
lightbox and multi indicator usage
=> additional detail added

c/time-picker/v1.0.0-beta.1/index.md
Times prior to the selected start time will not be in the list.
=> removed text

index.md
Updated the link from the elements site to NPM
=> Updated the link to dev site

c/alerts/v2.0.0-beta.3/index.md
=> change icon size

getting-started-dev/index.md
=> change to getting-started-dev doc to reflect merged Elements SDK

getting-started-dev/index.md
Hello All,
Please review my PR for updating the documentation on behalf of PDA QA.
It has links that refer to our Ux-Test-Framework location on github and ReadMe documents.
Thanks,
Payal
=> Update PDA QA documentation

c/forms/v1.1.0/index.md
beta versions should not appear under changelog of a published component
=> remove beta versions from changelog

_layouts/contact.html, _layouts/default.html, _sass/_article.scss, _sass/_home.scss, introduction.md, overview.md
@parkerpearson , I’ve defined the table style in the _articles.scss. I
just want to check with you if this would have any negative impact in
other places. thanks
=> Updated Overview Page
